export const GET_COMPANY_REQ = "GET_COMPANY_REQ";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAIL = "GET_COMPANY_FAIL";

export const POST_COMPANY_REQ =     "POST_COMPANY_REQ";
export const POST_COMPANY_SUCCESS = "POST_COMPANY_SUCCESS";
export const POST_COMPANY_FAIL =    "POST_COMPANY_FAIL";

export const GET_FILTER_REQ = "GET_FILTER_REQ";
export const GET_FILTER_SUCCESS = "GET_FILTER_SUCCESS";
export const GET_FILTER_FAIL = "GET_FILTER_FAIL";